export const CHAT_LOAD_MESSAGES_SUCCESS = 'CHAT_LOAD_MESSAGES_SUCCESS'
export const CHAT_LOAD_MESSAGES_ERROR = 'CHAT_LOAD_MESSAGES_ERROR'
export const CHAT_LOAD_FRIENDS_SUCCESS = 'CHAT_LOAD_FRIENDS_SUCCESS'
export const CHAT_LOAD_FRIENDS_ERROR = 'CHAT_LOAD_FRIENDS_ERROR'
